version: '3.3'
services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: '3307'
    ports:
      - '3307:3307'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--port", "3307", "-uuser", "-ppassword"]
        timeout: 5s
        retries: 10

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
     - my-redis:/var/lib/redis

  migrations:
    build: .
    command: ["yarn", "knex", "migrate:up"]
    depends_on:
      db:
          condition: service_healthy

  node:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      migrations:
        condition: service_completed_successfully
volumes:
  my-db:
  my-redis:
